name: Build Relaease

on:
  workflow_dispatch:
    branches:
      main

jobs:
  build:
    name: Build CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: setup Dependency
        run: mvn dependency:tree
      - name: compile and build code
        run: mvn compile package
      - name: release building
        id: create_relase
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release
        id: upload_release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_relase.outputs.upload_url }}
          asset_path: target/vndustry-1.jar
          asset_name: Release.jar
          asset_content_type: application/jar




